In [ ]:
#1. Write a Python Program to Add Two Matrices?

In [11]:
def AddMatrices(matrix1 , matrix2):
    result = [[0,0,0],
              [0,0,0],
              [0,0,0]]
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result[i][j] = matrix1[i][j] + matrix2[i][j]
    return result

In [12]:
matrix1 = [[1,2,3],
          [4,5,6],
          [7,8,9]]

matrix2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
result = AddMatrices(matrix1, matrix2)
for i in result:
    print(i)

[2, 4, 6]
[8, 10, 12]
[14, 16, 18]


In [ ]:
#2. Write a Python Program to Multiply Two Matrices?

In [44]:
import  numpy as np
def MultiplyMatrix(matrix1, matrix2):
    n = len(matrix1)
    m = len(matrix2[0])
    print(m,' ', m)
    result = np.zeros([n,m], dtype=int)
    for i in range(len(matrix1)):
        for j in range(len(matrix2[0])):
            for k in range(len(matrix2)):
                result[i][j]+=matrix1[i][k]*matrix2[k][j]
    return result

In [45]:
matrix1 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
matrix2 = [[1,2,3],
          [4,5,6],
          [7,8,9]]
MultiplyMatrix(matrix1 , matrix2)

3   3


array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
#3. Write a Python Program to Transpose a Matrix?

In [65]:
import numpy as np
def TransposeMatrix(matrix1):
    result = np.zeros([len(matrix1[0]), len(matrix1)], dtype = int)
    print(result)
    for i in range(len(matrix1)):
        for j in range(len(matrix1[0])):
            result[j][i] = matrix1[i][j]
    
    return result

In [66]:
matrix = [[1,2],
          [4,5],
          [7,8]]
TransposeMatrix(matrix)

[[0 0 0]
 [0 0 0]]


array([[1, 4, 7],
       [2, 5, 8]])

In [ ]:
#4. Write a Python Program to Sort Words in Alphabetic Order?

In [71]:
def SortWords(s):
    s = s.lower()
    w = s.split(' ')
    w.sort()
    return w

In [72]:
SortWords('Hi my name is Ritesh Shirude')

['hi', 'is', 'my', 'name', 'ritesh', 'shirude']

In [ ]:
#5. Write a Python Program to Remove Punctuation From a String?

In [89]:
def RemovePunctuation(s):
    punct = '''!'''
    newS = ''
    for i in s:
        if i not in punct:
            newS += i 
    return newS

In [90]:
RemovePunctuation('Hi ! my name is Ritesh Shirude !')

'Hi  my name is Ritesh Shirude '